language: php
php:
  - 5.5
  - 5.6
before_script:
  - sh -c "if [ $TRAVIS_PHP_VERSION != 'hhvm' ] && [ $TRAVIS_PHP_VERSION != 'nightly' ] && [ `php-config --vernum` -ge 50500 ] ; then pecl config-set preferred_state beta; printf "yes\n" | pecl install -f apcu ; else echo 'extension="apc.so"' >> ./apc.ini ; fi"
  - sh -c "if [ $TRAVIS_PHP_VERSION != 'hhvm' ] && [ $TRAVIS_PHP_VERSION != 'nightly' ] ; then phpenv config-add ./apc.ini; fi"
  - ./create_config.sh
  - composer install
script:
  - php -f sdk/index.php | grep -q "MB PREMIUM TECH T"
  - php -f raw/index.php | grep -q "MB PREMIUM TECH T"
env:
  global:
    - secure: SN8EIQiUvhp5tANd3i/HCwjwla3MYHtplt/+dnQ/N8oOlt/1NRn5Cc5nHbBgf6cBXFJe4sq70fsjzMy4smRKXQmPd+nb5wBfWbX2Hqs90qKF7sCWNy/UGtqwGCl7+64mG9YYi1Iky3eteNIfYmUf+NYehCf9iJt3KGGPT6J/Jp0=
    - secure: eQBhcawm0NfGIW9cOBfEsrDtEt0G+Lb6gdVzIbf0g7WyVeiPw1SBkDt2c2HJ3XgWfs04tL35n/prhyrlaswrsWMvSDaQ1Tx4kdSeyWJb5yEPTIwQvqU78lgi5pS4DN6y0xLoBUPmwtOLfS+jdJVS45uPhDkEF9RH7KT6ZRCugm4=
    - secure: q31tDjWyEywxdGQIZprOkrBSPkvuhGvHwUgG60BzePhYsuIGxcP1lL1Y+65cUWh2CfrFw1t43VAY0TFe6Bz1VyquG45Wt3Iey+Rw3vJt59KQ/5t1WRXYlXKixF4oiy2AxyN4v0nOlCfHOCSXBgJlqIxnTbQafavkatArikkRIfk=
